### ISSUE TITLE
[Android SDK] - Email Login

### ISSUE THREAD

**Issue by PhillipiLino** [ingresse/android-sdk#2]
#### Descrição

Implementação das chamadas do fluxo de email login no SDK e fazer a verificação das chamadas no aplicativo android com o retorno das respostas da API.

### Login sucesso
1. realizar login de um usuário cadastrado na plataforma
2. verificar se usuário está logado corretamente

### Login E-mail Incorreto
1. realiza login de um usuário passando e-mail incorreto
2. verificar se mensagem de erro tratada aparece

### Login Senha Incorreta
1. realizar login de um usuário passando senha incorreta
2. verificar se mensagem de erro tratada aparece

**Obs:** esse tarefa só dá para ser testada quando houver alguma outra tarefa relacionada ao app android

**Comment by vivianeferreira** [comment]
## Comentário:
Aguardando correção da issue: #271 - [Login] Refactor - Login por email
