### ISSUE TITLE
[Backstage] Chamada de event list

### ISSUE THREAD

**Issue by gondekr** [ingresse/android-sdk#28]
## Descrição
Transportar a chamada de event-list do backstage para o sdk

### Endpoint 
__URL:__ _https://event.ingresse.com/search/producer/_
__Parametros (Header):__
- JWT Token
 
__Parametros (Query):__ 
- size
- orderBy = "sessions.dateTime"
- from = "now-1d"
- to = "now-1d"
- offset

**Comment by vivianeferreira** [comment]
@tmikulsk1 

## Correções:
- [ ] Ao cancelar uma venda na bilheteria o sistema redireciona para a antiga tela de lista de eventos;
- [ ] Ao cancelar uma venda na bilheteria e clicar no botão voltar ele retorna para a tela anterior de compra;
- [ ] Ao comprar ingresso sem estoque aparece mensagem "OPS! 6004";
- [ ] Ao finalizar uma venda na bilheteria o sistema redireciona para a antiga tela de lista de eventos;
- [ ] No relatório de vendas, aparece um botão que redireciona para a bilheteria, porém ele não carrega.

**Comment by tmikulsk1** [comment]
@vivianeferreira esses erros são em relação ao backstage-android e não sdk. Por favor, coloca lá na issue correta esses erros.

**Comment by vivianeferreira** [comment]
@tmikulsk1 ok, inserido
